services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafiodb
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-db:/var/lib/postgresql/data