services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafiodb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
  app:
    build: .
    container_name: nest_app
    restart: unless-stopped
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}